// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_report_to_ffi`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ScanJob`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Devuelve la revision del motor nativo.
int engineRevision() => RustLib.instance.api.crateApiEngineRevision();

/// Inicializa el motor con token de capacidad y directorio de trabajo.
Future<EngineInfoFfi> engineInit({
  required String capabilityToken,
  required String dataDir,
}) => RustLib.instance.api.crateApiEngineInit(
  capabilityToken: capabilityToken,
  dataDir: dataDir,
);

/// Enumera las unidades del sistema (USB, SSD, HDD).
Future<List<VolumeInfoFfi>> listSystemVolumes() =>
    RustLib.instance.api.crateApiListSystemVolumes();

/// Analiza un unico archivo de audio usando el motor DSP y de veredicto completo.
Future<FileReportFfi> analyzeFile({required String path}) =>
    RustLib.instance.api.crateApiAnalyzeFile(path: path);

/// Analisis rapido preliminar (alias compatible).
Future<FileReportFfi> analyzeFileQuick({required String path}) =>
    RustLib.instance.api.crateApiAnalyzeFileQuick(path: path);

/// Analiza un lote de archivos seleccionados.
Future<List<FileReportFfi>> analyzeBatch({required List<String> paths}) =>
    RustLib.instance.api.crateApiAnalyzeBatch(paths: paths);

/// Inicia un trabajo de escaneo masivo asincrono en segundo plano (soporta 100.000+ pistas).
Future<PlatformInt64> startScanJob({
  required List<String> roots,
  required String throttleMode,
  required bool skipCache,
}) => RustLib.instance.api.crateApiStartScanJob(
  roots: roots,
  throttleMode: throttleMode,
  skipCache: skipCache,
);

/// Consulta el progreso y recoge nuevos reportes generados desde la ultima consulta.
Future<ScanJobStatusFfi> pollScanJob({required PlatformInt64 jobId}) =>
    RustLib.instance.api.crateApiPollScanJob(jobId: jobId);

/// Cancela un trabajo de escaneo especifico en tiempo real.
Future<bool> cancelScanJob({required PlatformInt64 jobId}) =>
    RustLib.instance.api.crateApiCancelScanJob(jobId: jobId);

/// Cancela todos los trabajos de escaneo activos inmediatamente.
Future<bool> cancelAllScans() => RustLib.instance.api.crateApiCancelAllScans();

/// Escanea una carpeta o unidad y analiza hasta `max_files` archivos de audio encontrados (0 para ilimitado).
Future<List<FileReportFfi>> scanDirectoryAudio({
  required String rootPath,
  required int maxFiles,
}) => RustLib.instance.api.crateApiScanDirectoryAudio(
  rootPath: rootPath,
  maxFiles: maxFiles,
);

/// Consulta reportes guardados en la base de datos local SQLite.
Future<List<FileReportFfi>> querySavedReports({
  String? verdictFilter,
  String? search,
  required int limit,
  required int offset,
}) => RustLib.instance.api.crateApiQuerySavedReports(
  verdictFilter: verdictFilter,
  search: search,
  limit: limit,
  offset: offset,
);

/// Cuenta el total de reportes que coinciden con los filtros.
Future<BigInt> countSavedReports({String? verdictFilter, String? search}) =>
    RustLib.instance.api.crateApiCountSavedReports(
      verdictFilter: verdictFilter,
      search: search,
    );

/// Encuentra grupos de pistas duplicadas agrupadas por su hash BLAKE3.
Future<List<DuplicateGroupFfi>> queryDuplicateGroups({
  required int limitGroups,
}) =>
    RustLib.instance.api.crateApiQueryDuplicateGroups(limitGroups: limitGroups);

/// Exporta los reportes guardados a archivo CSV de forma paginada y eficiente.
Future<bool> exportReportsCsv({required String outPath}) =>
    RustLib.instance.api.crateApiExportReportsCsv(outPath: outPath);

/// Exporta los reportes guardados a archivo JSON de forma paginada y eficiente.
Future<bool> exportReportsJson({required String outPath}) =>
    RustLib.instance.api.crateApiExportReportsJson(outPath: outPath);

/// Diagnostico interno del motor nativo.
Future<String> diagnostics() => RustLib.instance.api.crateApiDiagnostics();

class DuplicateGroupFfi {
  final String blake3Hash;
  final BigInt count;
  final BigInt fileSize;
  final List<FileReportFfi> reports;

  const DuplicateGroupFfi({
    required this.blake3Hash,
    required this.count,
    required this.fileSize,
    required this.reports,
  });

  @override
  int get hashCode =>
      blake3Hash.hashCode ^
      count.hashCode ^
      fileSize.hashCode ^
      reports.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DuplicateGroupFfi &&
          runtimeType == other.runtimeType &&
          blake3Hash == other.blake3Hash &&
          count == other.count &&
          fileSize == other.fileSize &&
          reports == other.reports;
}

class EngineInfoFfi {
  final int revision;
  final String dataDir;
  final String status;

  const EngineInfoFfi({
    required this.revision,
    required this.dataDir,
    required this.status,
  });

  @override
  int get hashCode => revision.hashCode ^ dataDir.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineInfoFfi &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          dataDir == other.dataDir &&
          status == other.status;
}

class EvidenceFfi {
  final String code;
  final double? value;
  final double llr;
  final bool applicable;
  final String description;

  const EvidenceFfi({
    required this.code,
    this.value,
    required this.llr,
    required this.applicable,
    required this.description,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      value.hashCode ^
      llr.hashCode ^
      applicable.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvidenceFfi &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          value == other.value &&
          llr == other.llr &&
          applicable == other.applicable &&
          description == other.description;
}

class FileReportFfi {
  final PlatformInt64 fileId;
  final String path;
  final BigInt fileSize;
  final int engineRev;
  final FormatFactsFfi facts;
  final String verdictCode;
  final String verdictName;
  final double confidence;
  final double scoreLlr;
  final int? effectiveBandwidthHz;
  final double? cutoffSlopeDbOct;
  final List<EvidenceFfi> evidences;
  final QualityMetricsFfi quality;
  final List<String> guardsTriggered;
  final String verdictSummary;
  final Float32List spectrumDb;

  const FileReportFfi({
    required this.fileId,
    required this.path,
    required this.fileSize,
    required this.engineRev,
    required this.facts,
    required this.verdictCode,
    required this.verdictName,
    required this.confidence,
    required this.scoreLlr,
    this.effectiveBandwidthHz,
    this.cutoffSlopeDbOct,
    required this.evidences,
    required this.quality,
    required this.guardsTriggered,
    required this.verdictSummary,
    required this.spectrumDb,
  });

  @override
  int get hashCode =>
      fileId.hashCode ^
      path.hashCode ^
      fileSize.hashCode ^
      engineRev.hashCode ^
      facts.hashCode ^
      verdictCode.hashCode ^
      verdictName.hashCode ^
      confidence.hashCode ^
      scoreLlr.hashCode ^
      effectiveBandwidthHz.hashCode ^
      cutoffSlopeDbOct.hashCode ^
      evidences.hashCode ^
      quality.hashCode ^
      guardsTriggered.hashCode ^
      verdictSummary.hashCode ^
      spectrumDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileReportFfi &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          path == other.path &&
          fileSize == other.fileSize &&
          engineRev == other.engineRev &&
          facts == other.facts &&
          verdictCode == other.verdictCode &&
          verdictName == other.verdictName &&
          confidence == other.confidence &&
          scoreLlr == other.scoreLlr &&
          effectiveBandwidthHz == other.effectiveBandwidthHz &&
          cutoffSlopeDbOct == other.cutoffSlopeDbOct &&
          evidences == other.evidences &&
          quality == other.quality &&
          guardsTriggered == other.guardsTriggered &&
          verdictSummary == other.verdictSummary &&
          spectrumDb == other.spectrumDb;
}

class FormatFactsFfi {
  final String container;
  final String codec;
  final int sampleRate;
  final int? bitDepth;
  final int channels;
  final BigInt durationMs;
  final int? containerBitrateKbps;
  final bool isLosslessDeclared;

  const FormatFactsFfi({
    required this.container,
    required this.codec,
    required this.sampleRate,
    this.bitDepth,
    required this.channels,
    required this.durationMs,
    this.containerBitrateKbps,
    required this.isLosslessDeclared,
  });

  @override
  int get hashCode =>
      container.hashCode ^
      codec.hashCode ^
      sampleRate.hashCode ^
      bitDepth.hashCode ^
      channels.hashCode ^
      durationMs.hashCode ^
      containerBitrateKbps.hashCode ^
      isLosslessDeclared.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatFactsFfi &&
          runtimeType == other.runtimeType &&
          container == other.container &&
          codec == other.codec &&
          sampleRate == other.sampleRate &&
          bitDepth == other.bitDepth &&
          channels == other.channels &&
          durationMs == other.durationMs &&
          containerBitrateKbps == other.containerBitrateKbps &&
          isLosslessDeclared == other.isLosslessDeclared;
}

class QualityMetricsFfi {
  final double? truePeakDbtp;
  final double? lufsIntegrated;
  final BigInt clippedSamples;
  final double? dcOffset;
  final double? dynamicRangeDb;
  final double? stereoCorrelation;

  const QualityMetricsFfi({
    this.truePeakDbtp,
    this.lufsIntegrated,
    required this.clippedSamples,
    this.dcOffset,
    this.dynamicRangeDb,
    this.stereoCorrelation,
  });

  @override
  int get hashCode =>
      truePeakDbtp.hashCode ^
      lufsIntegrated.hashCode ^
      clippedSamples.hashCode ^
      dcOffset.hashCode ^
      dynamicRangeDb.hashCode ^
      stereoCorrelation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QualityMetricsFfi &&
          runtimeType == other.runtimeType &&
          truePeakDbtp == other.truePeakDbtp &&
          lufsIntegrated == other.lufsIntegrated &&
          clippedSamples == other.clippedSamples &&
          dcOffset == other.dcOffset &&
          dynamicRangeDb == other.dynamicRangeDb &&
          stereoCorrelation == other.stereoCorrelation;
}

class ScanJobStatusFfi {
  final PlatformInt64 jobId;
  final bool isActive;
  final bool isCompleted;
  final BigInt totalFound;
  final BigInt analyzedCount;
  final String currentPath;
  final List<FileReportFfi> newReports;

  const ScanJobStatusFfi({
    required this.jobId,
    required this.isActive,
    required this.isCompleted,
    required this.totalFound,
    required this.analyzedCount,
    required this.currentPath,
    required this.newReports,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      isActive.hashCode ^
      isCompleted.hashCode ^
      totalFound.hashCode ^
      analyzedCount.hashCode ^
      currentPath.hashCode ^
      newReports.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanJobStatusFfi &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          isActive == other.isActive &&
          isCompleted == other.isCompleted &&
          totalFound == other.totalFound &&
          analyzedCount == other.analyzedCount &&
          currentPath == other.currentPath &&
          newReports == other.newReports;
}

class VolumeInfoFfi {
  final int id;
  final String path;
  final String label;
  final String fsType;
  final bool isRemovable;
  final bool isReady;
  final BigInt totalBytes;
  final BigInt freeBytes;

  const VolumeInfoFfi({
    required this.id,
    required this.path,
    required this.label,
    required this.fsType,
    required this.isRemovable,
    required this.isReady,
    required this.totalBytes,
    required this.freeBytes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      label.hashCode ^
      fsType.hashCode ^
      isRemovable.hashCode ^
      isReady.hashCode ^
      totalBytes.hashCode ^
      freeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VolumeInfoFfi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          label == other.label &&
          fsType == other.fsType &&
          isRemovable == other.isRemovable &&
          isReady == other.isReady &&
          totalBytes == other.totalBytes &&
          freeBytes == other.freeBytes;
}
