// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1495887897;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'bdja_ffi',
        ioDirectory: '../engine/bdja_ffi/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<FileReportFfi>> crateApiAnalyzeBatch({
    required List<String> paths,
  });

  Future<FileReportFfi> crateApiAnalyzeFile({required String path});

  Future<FileReportFfi> crateApiAnalyzeFileQuick({required String path});

  Future<bool> crateApiCancelAllScans();

  Future<bool> crateApiCancelScanJob({required PlatformInt64 jobId});

  Future<BigInt> crateApiCountSavedReports({
    String? verdictFilter,
    String? search,
  });

  Future<List<String>> crateApiDeriveNativeHwidCandidates();

  Future<String> crateApiDiagnostics();

  Future<EngineInfoFfi> crateApiEngineInit({
    required String capabilityToken,
    required String dataDir,
  });

  int crateApiEngineRevision();

  Future<bool> crateApiExportReportsCsv({required String outPath});

  Future<bool> crateApiExportReportsJson({required String outPath});

  Future<List<VolumeInfoFfi>> crateApiListSystemVolumes();

  Future<ScanJobStatusFfi> crateApiPollScanJob({required PlatformInt64 jobId});

  Future<List<DuplicateGroupFfi>> crateApiQueryDuplicateGroups({
    required int limitGroups,
  });

  Future<List<FileReportFfi>> crateApiQuerySavedReports({
    String? verdictFilter,
    String? search,
    required int limit,
    required int offset,
  });

  Future<List<FileReportFfi>> crateApiScanDirectoryAudio({
    required String rootPath,
    required int maxFiles,
  });

  Future<PlatformInt64> crateApiStartScanJob({
    required List<String> roots,
    required String throttleMode,
    required bool skipCache,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<FileReportFfi>> crateApiAnalyzeBatch({
    required List<String> paths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(paths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_file_report_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAnalyzeBatchConstMeta,
        argValues: [paths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzeBatchConstMeta =>
      const TaskConstMeta(debugName: "analyze_batch", argNames: ["paths"]);

  @override
  Future<FileReportFfi> crateApiAnalyzeFile({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_file_report_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAnalyzeFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzeFileConstMeta =>
      const TaskConstMeta(debugName: "analyze_file", argNames: ["path"]);

  @override
  Future<FileReportFfi> crateApiAnalyzeFileQuick({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_file_report_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAnalyzeFileQuickConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzeFileQuickConstMeta =>
      const TaskConstMeta(debugName: "analyze_file_quick", argNames: ["path"]);

  @override
  Future<bool> crateApiCancelAllScans() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCancelAllScansConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCancelAllScansConstMeta =>
      const TaskConstMeta(debugName: "cancel_all_scans", argNames: []);

  @override
  Future<bool> crateApiCancelScanJob({required PlatformInt64 jobId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(jobId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCancelScanJobConstMeta,
        argValues: [jobId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCancelScanJobConstMeta =>
      const TaskConstMeta(debugName: "cancel_scan_job", argNames: ["jobId"]);

  @override
  Future<BigInt> crateApiCountSavedReports({
    String? verdictFilter,
    String? search,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(verdictFilter, serializer);
          sse_encode_opt_String(search, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCountSavedReportsConstMeta,
        argValues: [verdictFilter, search],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCountSavedReportsConstMeta => const TaskConstMeta(
    debugName: "count_saved_reports",
    argNames: ["verdictFilter", "search"],
  );

  @override
  Future<List<String>> crateApiDeriveNativeHwidCandidates() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeriveNativeHwidCandidatesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveNativeHwidCandidatesConstMeta =>
      const TaskConstMeta(
        debugName: "derive_native_hwid_candidates",
        argNames: [],
      );

  @override
  Future<String> crateApiDiagnostics() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDiagnosticsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiagnosticsConstMeta =>
      const TaskConstMeta(debugName: "diagnostics", argNames: []);

  @override
  Future<EngineInfoFfi> crateApiEngineInit({
    required String capabilityToken,
    required String dataDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(capabilityToken, serializer);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_engine_info_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEngineInitConstMeta,
        argValues: [capabilityToken, dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineInitConstMeta => const TaskConstMeta(
    debugName: "engine_init",
    argNames: ["capabilityToken", "dataDir"],
  );

  @override
  int crateApiEngineRevision() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineRevisionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineRevisionConstMeta =>
      const TaskConstMeta(debugName: "engine_revision", argNames: []);

  @override
  Future<bool> crateApiExportReportsCsv({required String outPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(outPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiExportReportsCsvConstMeta,
        argValues: [outPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportReportsCsvConstMeta => const TaskConstMeta(
    debugName: "export_reports_csv",
    argNames: ["outPath"],
  );

  @override
  Future<bool> crateApiExportReportsJson({required String outPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(outPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiExportReportsJsonConstMeta,
        argValues: [outPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportReportsJsonConstMeta => const TaskConstMeta(
    debugName: "export_reports_json",
    argNames: ["outPath"],
  );

  @override
  Future<List<VolumeInfoFfi>> crateApiListSystemVolumes() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_volume_info_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListSystemVolumesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListSystemVolumesConstMeta =>
      const TaskConstMeta(debugName: "list_system_volumes", argNames: []);

  @override
  Future<ScanJobStatusFfi> crateApiPollScanJob({required PlatformInt64 jobId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(jobId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scan_job_status_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPollScanJobConstMeta,
        argValues: [jobId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPollScanJobConstMeta =>
      const TaskConstMeta(debugName: "poll_scan_job", argNames: ["jobId"]);

  @override
  Future<List<DuplicateGroupFfi>> crateApiQueryDuplicateGroups({
    required int limitGroups,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(limitGroups, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_duplicate_group_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQueryDuplicateGroupsConstMeta,
        argValues: [limitGroups],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryDuplicateGroupsConstMeta =>
      const TaskConstMeta(
        debugName: "query_duplicate_groups",
        argNames: ["limitGroups"],
      );

  @override
  Future<List<FileReportFfi>> crateApiQuerySavedReports({
    String? verdictFilter,
    String? search,
    required int limit,
    required int offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(verdictFilter, serializer);
          sse_encode_opt_String(search, serializer);
          sse_encode_u_32(limit, serializer);
          sse_encode_u_32(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_file_report_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQuerySavedReportsConstMeta,
        argValues: [verdictFilter, search, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQuerySavedReportsConstMeta => const TaskConstMeta(
    debugName: "query_saved_reports",
    argNames: ["verdictFilter", "search", "limit", "offset"],
  );

  @override
  Future<List<FileReportFfi>> crateApiScanDirectoryAudio({
    required String rootPath,
    required int maxFiles,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootPath, serializer);
          sse_encode_u_32(maxFiles, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_file_report_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScanDirectoryAudioConstMeta,
        argValues: [rootPath, maxFiles],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanDirectoryAudioConstMeta => const TaskConstMeta(
    debugName: "scan_directory_audio",
    argNames: ["rootPath", "maxFiles"],
  );

  @override
  Future<PlatformInt64> crateApiStartScanJob({
    required List<String> roots,
    required String throttleMode,
    required bool skipCache,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(roots, serializer);
          sse_encode_String(throttleMode, serializer);
          sse_encode_bool(skipCache, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStartScanJobConstMeta,
        argValues: [roots, throttleMode, skipCache],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartScanJobConstMeta => const TaskConstMeta(
    debugName: "start_scan_job",
    argNames: ["roots", "throttleMode", "skipCache"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  DuplicateGroupFfi dco_decode_duplicate_group_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DuplicateGroupFfi(
      blake3Hash: dco_decode_String(arr[0]),
      count: dco_decode_u_64(arr[1]),
      fileSize: dco_decode_u_64(arr[2]),
      reports: dco_decode_list_file_report_ffi(arr[3]),
    );
  }

  @protected
  EngineInfoFfi dco_decode_engine_info_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EngineInfoFfi(
      revision: dco_decode_u_32(arr[0]),
      dataDir: dco_decode_String(arr[1]),
      status: dco_decode_String(arr[2]),
    );
  }

  @protected
  EvidenceFfi dco_decode_evidence_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return EvidenceFfi(
      code: dco_decode_String(arr[0]),
      value: dco_decode_opt_box_autoadd_f_64(arr[1]),
      llr: dco_decode_f_64(arr[2]),
      applicable: dco_decode_bool(arr[3]),
      description: dco_decode_String(arr[4]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FileReportFfi dco_decode_file_report_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return FileReportFfi(
      fileId: dco_decode_i_64(arr[0]),
      path: dco_decode_String(arr[1]),
      fileSize: dco_decode_u_64(arr[2]),
      engineRev: dco_decode_u_32(arr[3]),
      facts: dco_decode_format_facts_ffi(arr[4]),
      verdictCode: dco_decode_String(arr[5]),
      verdictName: dco_decode_String(arr[6]),
      confidence: dco_decode_f_64(arr[7]),
      scoreLlr: dco_decode_f_64(arr[8]),
      effectiveBandwidthHz: dco_decode_opt_box_autoadd_u_32(arr[9]),
      cutoffSlopeDbOct: dco_decode_opt_box_autoadd_f_64(arr[10]),
      evidences: dco_decode_list_evidence_ffi(arr[11]),
      quality: dco_decode_quality_metrics_ffi(arr[12]),
      guardsTriggered: dco_decode_list_String(arr[13]),
      verdictSummary: dco_decode_String(arr[14]),
      spectrumDb: dco_decode_list_prim_f_32_strict(arr[15]),
    );
  }

  @protected
  FormatFactsFfi dco_decode_format_facts_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return FormatFactsFfi(
      container: dco_decode_String(arr[0]),
      codec: dco_decode_String(arr[1]),
      sampleRate: dco_decode_u_32(arr[2]),
      bitDepth: dco_decode_opt_box_autoadd_u_16(arr[3]),
      channels: dco_decode_u_16(arr[4]),
      durationMs: dco_decode_u_64(arr[5]),
      containerBitrateKbps: dco_decode_opt_box_autoadd_u_32(arr[6]),
      isLosslessDeclared: dco_decode_bool(arr[7]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DuplicateGroupFfi> dco_decode_list_duplicate_group_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_duplicate_group_ffi).toList();
  }

  @protected
  List<EvidenceFfi> dco_decode_list_evidence_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_evidence_ffi).toList();
  }

  @protected
  List<FileReportFfi> dco_decode_list_file_report_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_file_report_ffi).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<VolumeInfoFfi> dco_decode_list_volume_info_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_volume_info_ffi).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  QualityMetricsFfi dco_decode_quality_metrics_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return QualityMetricsFfi(
      truePeakDbtp: dco_decode_opt_box_autoadd_f_64(arr[0]),
      lufsIntegrated: dco_decode_opt_box_autoadd_f_64(arr[1]),
      clippedSamples: dco_decode_u_64(arr[2]),
      dcOffset: dco_decode_opt_box_autoadd_f_64(arr[3]),
      dynamicRangeDb: dco_decode_opt_box_autoadd_f_64(arr[4]),
      stereoCorrelation: dco_decode_opt_box_autoadd_f_64(arr[5]),
    );
  }

  @protected
  ScanJobStatusFfi dco_decode_scan_job_status_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ScanJobStatusFfi(
      jobId: dco_decode_i_64(arr[0]),
      isActive: dco_decode_bool(arr[1]),
      isCompleted: dco_decode_bool(arr[2]),
      totalFound: dco_decode_u_64(arr[3]),
      analyzedCount: dco_decode_u_64(arr[4]),
      currentPath: dco_decode_String(arr[5]),
      newReports: dco_decode_list_file_report_ffi(arr[6]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VolumeInfoFfi dco_decode_volume_info_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return VolumeInfoFfi(
      id: dco_decode_u_8(arr[0]),
      path: dco_decode_String(arr[1]),
      label: dco_decode_String(arr[2]),
      fsType: dco_decode_String(arr[3]),
      isRemovable: dco_decode_bool(arr[4]),
      isReady: dco_decode_bool(arr[5]),
      totalBytes: dco_decode_u_64(arr[6]),
      freeBytes: dco_decode_u_64(arr[7]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  DuplicateGroupFfi sse_decode_duplicate_group_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_blake3Hash = sse_decode_String(deserializer);
    var var_count = sse_decode_u_64(deserializer);
    var var_fileSize = sse_decode_u_64(deserializer);
    var var_reports = sse_decode_list_file_report_ffi(deserializer);
    return DuplicateGroupFfi(
      blake3Hash: var_blake3Hash,
      count: var_count,
      fileSize: var_fileSize,
      reports: var_reports,
    );
  }

  @protected
  EngineInfoFfi sse_decode_engine_info_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_revision = sse_decode_u_32(deserializer);
    var var_dataDir = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    return EngineInfoFfi(
      revision: var_revision,
      dataDir: var_dataDir,
      status: var_status,
    );
  }

  @protected
  EvidenceFfi sse_decode_evidence_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_value = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_llr = sse_decode_f_64(deserializer);
    var var_applicable = sse_decode_bool(deserializer);
    var var_description = sse_decode_String(deserializer);
    return EvidenceFfi(
      code: var_code,
      value: var_value,
      llr: var_llr,
      applicable: var_applicable,
      description: var_description,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FileReportFfi sse_decode_file_report_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileId = sse_decode_i_64(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_fileSize = sse_decode_u_64(deserializer);
    var var_engineRev = sse_decode_u_32(deserializer);
    var var_facts = sse_decode_format_facts_ffi(deserializer);
    var var_verdictCode = sse_decode_String(deserializer);
    var var_verdictName = sse_decode_String(deserializer);
    var var_confidence = sse_decode_f_64(deserializer);
    var var_scoreLlr = sse_decode_f_64(deserializer);
    var var_effectiveBandwidthHz = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_cutoffSlopeDbOct = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_evidences = sse_decode_list_evidence_ffi(deserializer);
    var var_quality = sse_decode_quality_metrics_ffi(deserializer);
    var var_guardsTriggered = sse_decode_list_String(deserializer);
    var var_verdictSummary = sse_decode_String(deserializer);
    var var_spectrumDb = sse_decode_list_prim_f_32_strict(deserializer);
    return FileReportFfi(
      fileId: var_fileId,
      path: var_path,
      fileSize: var_fileSize,
      engineRev: var_engineRev,
      facts: var_facts,
      verdictCode: var_verdictCode,
      verdictName: var_verdictName,
      confidence: var_confidence,
      scoreLlr: var_scoreLlr,
      effectiveBandwidthHz: var_effectiveBandwidthHz,
      cutoffSlopeDbOct: var_cutoffSlopeDbOct,
      evidences: var_evidences,
      quality: var_quality,
      guardsTriggered: var_guardsTriggered,
      verdictSummary: var_verdictSummary,
      spectrumDb: var_spectrumDb,
    );
  }

  @protected
  FormatFactsFfi sse_decode_format_facts_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_container = sse_decode_String(deserializer);
    var var_codec = sse_decode_String(deserializer);
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_bitDepth = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_channels = sse_decode_u_16(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_containerBitrateKbps = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_isLosslessDeclared = sse_decode_bool(deserializer);
    return FormatFactsFfi(
      container: var_container,
      codec: var_codec,
      sampleRate: var_sampleRate,
      bitDepth: var_bitDepth,
      channels: var_channels,
      durationMs: var_durationMs,
      containerBitrateKbps: var_containerBitrateKbps,
      isLosslessDeclared: var_isLosslessDeclared,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DuplicateGroupFfi> sse_decode_list_duplicate_group_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DuplicateGroupFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_duplicate_group_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  List<EvidenceFfi> sse_decode_list_evidence_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EvidenceFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_evidence_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  List<FileReportFfi> sse_decode_list_file_report_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FileReportFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_file_report_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<VolumeInfoFfi> sse_decode_list_volume_info_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VolumeInfoFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_volume_info_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QualityMetricsFfi sse_decode_quality_metrics_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_truePeakDbtp = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_lufsIntegrated = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_clippedSamples = sse_decode_u_64(deserializer);
    var var_dcOffset = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_dynamicRangeDb = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_stereoCorrelation = sse_decode_opt_box_autoadd_f_64(deserializer);
    return QualityMetricsFfi(
      truePeakDbtp: var_truePeakDbtp,
      lufsIntegrated: var_lufsIntegrated,
      clippedSamples: var_clippedSamples,
      dcOffset: var_dcOffset,
      dynamicRangeDb: var_dynamicRangeDb,
      stereoCorrelation: var_stereoCorrelation,
    );
  }

  @protected
  ScanJobStatusFfi sse_decode_scan_job_status_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_jobId = sse_decode_i_64(deserializer);
    var var_isActive = sse_decode_bool(deserializer);
    var var_isCompleted = sse_decode_bool(deserializer);
    var var_totalFound = sse_decode_u_64(deserializer);
    var var_analyzedCount = sse_decode_u_64(deserializer);
    var var_currentPath = sse_decode_String(deserializer);
    var var_newReports = sse_decode_list_file_report_ffi(deserializer);
    return ScanJobStatusFfi(
      jobId: var_jobId,
      isActive: var_isActive,
      isCompleted: var_isCompleted,
      totalFound: var_totalFound,
      analyzedCount: var_analyzedCount,
      currentPath: var_currentPath,
      newReports: var_newReports,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VolumeInfoFfi sse_decode_volume_info_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_8(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_fsType = sse_decode_String(deserializer);
    var var_isRemovable = sse_decode_bool(deserializer);
    var var_isReady = sse_decode_bool(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_freeBytes = sse_decode_u_64(deserializer);
    return VolumeInfoFfi(
      id: var_id,
      path: var_path,
      label: var_label,
      fsType: var_fsType,
      isRemovable: var_isRemovable,
      isReady: var_isReady,
      totalBytes: var_totalBytes,
      freeBytes: var_freeBytes,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_duplicate_group_ffi(
    DuplicateGroupFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.blake3Hash, serializer);
    sse_encode_u_64(self.count, serializer);
    sse_encode_u_64(self.fileSize, serializer);
    sse_encode_list_file_report_ffi(self.reports, serializer);
  }

  @protected
  void sse_encode_engine_info_ffi(
    EngineInfoFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.revision, serializer);
    sse_encode_String(self.dataDir, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_evidence_ffi(EvidenceFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_opt_box_autoadd_f_64(self.value, serializer);
    sse_encode_f_64(self.llr, serializer);
    sse_encode_bool(self.applicable, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_file_report_ffi(
    FileReportFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.fileId, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_u_64(self.fileSize, serializer);
    sse_encode_u_32(self.engineRev, serializer);
    sse_encode_format_facts_ffi(self.facts, serializer);
    sse_encode_String(self.verdictCode, serializer);
    sse_encode_String(self.verdictName, serializer);
    sse_encode_f_64(self.confidence, serializer);
    sse_encode_f_64(self.scoreLlr, serializer);
    sse_encode_opt_box_autoadd_u_32(self.effectiveBandwidthHz, serializer);
    sse_encode_opt_box_autoadd_f_64(self.cutoffSlopeDbOct, serializer);
    sse_encode_list_evidence_ffi(self.evidences, serializer);
    sse_encode_quality_metrics_ffi(self.quality, serializer);
    sse_encode_list_String(self.guardsTriggered, serializer);
    sse_encode_String(self.verdictSummary, serializer);
    sse_encode_list_prim_f_32_strict(self.spectrumDb, serializer);
  }

  @protected
  void sse_encode_format_facts_ffi(
    FormatFactsFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.container, serializer);
    sse_encode_String(self.codec, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_opt_box_autoadd_u_16(self.bitDepth, serializer);
    sse_encode_u_16(self.channels, serializer);
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.containerBitrateKbps, serializer);
    sse_encode_bool(self.isLosslessDeclared, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_duplicate_group_ffi(
    List<DuplicateGroupFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_duplicate_group_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_list_evidence_ffi(
    List<EvidenceFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_evidence_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_list_file_report_ffi(
    List<FileReportFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_file_report_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_volume_info_ffi(
    List<VolumeInfoFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_volume_info_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_quality_metrics_ffi(
    QualityMetricsFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_f_64(self.truePeakDbtp, serializer);
    sse_encode_opt_box_autoadd_f_64(self.lufsIntegrated, serializer);
    sse_encode_u_64(self.clippedSamples, serializer);
    sse_encode_opt_box_autoadd_f_64(self.dcOffset, serializer);
    sse_encode_opt_box_autoadd_f_64(self.dynamicRangeDb, serializer);
    sse_encode_opt_box_autoadd_f_64(self.stereoCorrelation, serializer);
  }

  @protected
  void sse_encode_scan_job_status_ffi(
    ScanJobStatusFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.jobId, serializer);
    sse_encode_bool(self.isActive, serializer);
    sse_encode_bool(self.isCompleted, serializer);
    sse_encode_u_64(self.totalFound, serializer);
    sse_encode_u_64(self.analyzedCount, serializer);
    sse_encode_String(self.currentPath, serializer);
    sse_encode_list_file_report_ffi(self.newReports, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_volume_info_ffi(
    VolumeInfoFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.id, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.fsType, serializer);
    sse_encode_bool(self.isRemovable, serializer);
    sse_encode_bool(self.isReady, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_u_64(self.freeBytes, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
