// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CutoffKindFfi dco_decode_box_autoadd_cutoff_kind_ffi(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CutoffKindFfi dco_decode_cutoff_kind_ffi(dynamic raw);

  @protected
  DuplicateGroupFfi dco_decode_duplicate_group_ffi(dynamic raw);

  @protected
  EngineInfoFfi dco_decode_engine_info_ffi(dynamic raw);

  @protected
  EvidenceFfi dco_decode_evidence_ffi(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FileReportFfi dco_decode_file_report_ffi(dynamic raw);

  @protected
  FormatFactsFfi dco_decode_format_facts_ffi(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DuplicateGroupFfi> dco_decode_list_duplicate_group_ffi(dynamic raw);

  @protected
  List<EvidenceFfi> dco_decode_list_evidence_ffi(dynamic raw);

  @protected
  List<FileReportFfi> dco_decode_list_file_report_ffi(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<VolumeInfoFfi> dco_decode_list_volume_info_ffi(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CutoffKindFfi? dco_decode_opt_box_autoadd_cutoff_kind_ffi(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  QualityMetricsFfi dco_decode_quality_metrics_ffi(dynamic raw);

  @protected
  ScanJobStatusFfi dco_decode_scan_job_status_ffi(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VolumeInfoFfi dco_decode_volume_info_ffi(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CutoffKindFfi sse_decode_box_autoadd_cutoff_kind_ffi(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CutoffKindFfi sse_decode_cutoff_kind_ffi(SseDeserializer deserializer);

  @protected
  DuplicateGroupFfi sse_decode_duplicate_group_ffi(
    SseDeserializer deserializer,
  );

  @protected
  EngineInfoFfi sse_decode_engine_info_ffi(SseDeserializer deserializer);

  @protected
  EvidenceFfi sse_decode_evidence_ffi(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FileReportFfi sse_decode_file_report_ffi(SseDeserializer deserializer);

  @protected
  FormatFactsFfi sse_decode_format_facts_ffi(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DuplicateGroupFfi> sse_decode_list_duplicate_group_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<EvidenceFfi> sse_decode_list_evidence_ffi(SseDeserializer deserializer);

  @protected
  List<FileReportFfi> sse_decode_list_file_report_ffi(
    SseDeserializer deserializer,
  );

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<VolumeInfoFfi> sse_decode_list_volume_info_ffi(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CutoffKindFfi? sse_decode_opt_box_autoadd_cutoff_kind_ffi(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  QualityMetricsFfi sse_decode_quality_metrics_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ScanJobStatusFfi sse_decode_scan_job_status_ffi(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VolumeInfoFfi sse_decode_volume_info_ffi(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cutoff_kind_ffi(
    CutoffKindFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_cutoff_kind_ffi(CutoffKindFfi self, SseSerializer serializer);

  @protected
  void sse_encode_duplicate_group_ffi(
    DuplicateGroupFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_engine_info_ffi(EngineInfoFfi self, SseSerializer serializer);

  @protected
  void sse_encode_evidence_ffi(EvidenceFfi self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_file_report_ffi(FileReportFfi self, SseSerializer serializer);

  @protected
  void sse_encode_format_facts_ffi(
    FormatFactsFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_duplicate_group_ffi(
    List<DuplicateGroupFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_evidence_ffi(
    List<EvidenceFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_report_ffi(
    List<FileReportFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_volume_info_ffi(
    List<VolumeInfoFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_cutoff_kind_ffi(
    CutoffKindFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_quality_metrics_ffi(
    QualityMetricsFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_job_status_ffi(
    ScanJobStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_volume_info_ffi(VolumeInfoFfi self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
